[package]
authors = ["Dimitri Merejkowsky <d.merej@gmail.com>"]
name = "dmenv"
version = "0.4.2"
description = "The stupid virtualenv manager"
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/TankerHQ/dmenv"

keywords = ["python", "virtualenv"]
categories = ["command-line-utilities"]

[dependencies]
appdirs = "0.2"
colored = "1.6"
structopt = "0.2"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
which = "2.0"

[dev-dependencies]
tempdir = "0.3"
