[version]
current = "0.14.0"

regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump to {new_version} [ci skip]"
tag_template = "v{new_version}"

[[file]]
src = "Cargo.toml"

[[before_push]]
name = "Check changelog"
cmd = "grep {new_version} CHANGELOG.md"

[[before_push]]
name = "Run tests"
cmd = "cargo test"

[[after_push]]
name = "publish"
cmd = "cargo publish"
