site_name: dmenv

docs_dir: contents
site_dir: site

theme:
  name: readthedocs

strict: true

markdown_extensions:
  - markdown.extensions.admonition #for !!! notice
  - markdown.extensions.def_list
  - footnotes

  - toc:
      permalink: True
      separator: "_"

nav:
  - Home: index.md

  - Installation: installation.md
  - Basic Usage: basic_usage.md
  - Goodies: goodies.md
  - Advanced Usage: advanced_usage.md

  - FAQ: faq.md

  - Changelog: changelog.md
